import { Navbar } from 'components/navbar/navbar'
import { FeaturesSection } from 'components/sections/features/features-section'
import { HeroSection } from 'components/sections/hero/hero-section'
import { ProductiveSection } from 'components/sections/productive/productive-section'
import { TestimonialsSection } from 'components/sections/testimonials/testimonials-section'
import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <HeroSection />
        <FeaturesSection />
        <ProductiveSection/>  
        <TestimonialsSection/>      
      </main>
     
    </>
  )
}

export default Home
