import { Navbar } from 'components/navbar/navbar'
import { HeroSection } from 'components/sections/hero/hero-section'
import type { NextPage } from 'next'
import Head from 'next/head'



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <HeroSection/>

      </main>
     
    </>
  )
}

export default Home
